FROM public.ecr.aws/lambda/python:3.13

RUN pip install --upgrade pip
RUN pip install torch \
    --extra-index-url https://download.pytorch.org/whl/cpu \
    transformers numpy

COPY text_classifier.py ./
CMD ["text_classifier.lambda_handler"]